apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
{{ include "app.namespace" . | indent 2 }}
spec:
  replicas: {{ .Values.db.replicas}}
{{ include "app.strategy" . | indent 2 }}
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=200
          image: {{ .Values.db.image }}
          name: db
          ports:
            - containerPort: {{ .Values.db.port }}
{{ include "db.resources" . | indent 10 }}
{{ include "db.envs" . | indent 10 }}
{{ include "db.probes" . | indent 10 }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-claim0
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0