apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-claim0
  name: db-claim0
{{ include "app.namespace" . | indent 2 }}
spec:
  accessModes:
    - {{ .Values.db.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}