apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: proxy
  name: proxy
{{ include "app.namespace" . | indent 2 }}
spec:
  replicas: {{ .Values.proxy.replicas }}
{{ include "app.strategy" . | indent 2 }}
  selector:
    matchLabels:
      io.kompose.service: proxy
  template:
    metadata:
      labels:
        io.kompose.service: proxy
    spec:
      containers:
        - env:
            - name: BACK_PROXY_PASS
              value: http://backend:4000
            - name: FRONT_PROXY_PASS
              value: http://frontend:3000
          name: proxy
          image: {{ .Values.proxy.image }}
          ports:
            - containerPort: 80
            - containerPort: 8080
            - containerPort: 8081
{{ include "backend.resources" . | indent 10 }}
          volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d/default.conf
            readOnly: true
            subPath: default.conf
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ .Values.proxy.name }}
      restartPolicy: Always