apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: redis-db-claim0
  name: redis-db-claim0
{{ include "app.namespace" . | indent 2 }}
spec:
  accessModes:
    - {{ .Values.redis.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}