apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sig-provider
  name: {{ .Values.sigprovider.name }}
{{ include "app.namespace" . | indent 2 }}
spec:
  ports:
    - name: {{ .Values.sigprovider.port | quote }}
      port: {{ .Values.sigprovider.port }}
      targetPort: {{ .Values.sigprovider.port }}
  selector:
    io.kompose.service: sig-provider

