apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: stats
  name: {{ .Values.stats.name }}
{{ include "app.namespace" . | indent 2 }}
spec:
  ports:
    - name: {{ .Values.stats.port | quote }}
      port: {{ .Values.stats.port }}
      targetPort: {{ .Values.stats.port }}
  selector:
    io.kompose.service: stats