---
# Source: Blockscout/templates/db-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-claim0
  name: db-claim0
  namespace: blockscout
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
