---
# Source: Blockscout/templates/proxy-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: proxy
  name: proxy
  namespace: blockscout
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      io.kompose.service: proxy
  template:
    metadata:
      labels:
        io.kompose.service: proxy
    spec:
      containers:
        - env:
            - name: BACK_PROXY_PASS
              value: http://backend:4000
            - name: FRONT_PROXY_PASS
              value: http://frontend:3000
          name: proxy
          image: nginx
          ports:
            - containerPort: 80
            - containerPort: 8080
            - containerPort: 8081
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d/default.conf
            readOnly: true
            subPath: default.conf
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: proxy
      restartPolicy: Always
