---
# Source: Blockscout/templates/proxy-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: proxy
  name: proxy
  namespace: blockscout
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: proxy
