---
# Source: Blockscout/templates/redis-db-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis-db
  name: redis-db
  namespace: blockscout
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis-db
