---
# Source: Blockscout/templates/sig-provider-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sig-provider
  name: sig-provider
  namespace: blockscout
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      io.kompose.service: sig-provider
  template:
    metadata:
      labels:
        io.kompose.service: sig-provider
    spec:
      containers:
        - image: ghcr.io/blockscout/sig-provider:latest
          name: sig-provider
          ports:
            - containerPort: 8050
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Always
