---
# Source: Blockscout/templates/stats-db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: stats-db
  name: stats-db
  namespace: blockscout
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      io.kompose.service: stats-db
  template:
    metadata:
      labels:
        io.kompose.service: stats-db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=200
          image: postgres:14
          name: stats-postgres
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: POSTGRES_DB
              value: stats
            - name: POSTGRES_PASSWORD
              value: n0uejXPl61ci6ldCuE2gQU5Y
            - name: POSTGRES_USER
              value: stats
          livenessProbe:
            exec:
              command:
                - pg_isready -U stats -d stats
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: stats-db-claim0
      restartPolicy: Always
      volumes:
        - name: stats-db-claim0
          persistentVolumeClaim:
            claimName: stats-db-claim0
