---
# Source: Blockscout/templates/visualizer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: visualizer
  name: visualizer
  namespace: blockscout
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      io.kompose.service: visualizer
  template:
    metadata:
      labels:
        io.kompose.service: visualizer
    spec:
      containers:
        - name: visualizer
          image: ghcr.io/blockscout/visualizer:latest
          ports:
            - containerPort: 
          env:
            - name: VISUALIZER__SERVER__GRPC__ENABLED
              valueFrom:
                configMapKeyRef:
                  key: VISUALIZER__SERVER__GRPC__ENABLED
                  name: envs-common-visualizer-env
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Always
