stages:
  - helm_lint


before_script:
  - TXT_RED="\e[31m"    # https://docs.gitlab.com/ee/ci/yaml/script.html#add-color-codes-to-script-output , https://misc.flogisoft.com/bash/tip_colors_and_formatting
  - TXT_GREEN="\e[32m"
  - TXT_YELLOW="\e[33m"
  - TXT_CLEAR="\e[0m"
  - HELM_REPO_SERVER="http://chartmuseum.example.com"
  - HELM_REPO_URI="/api/charts"

chart-helm-lint:
  image: helm:3.2.4
  stage: helm_lint
  tags:
    - docker
  script:
    - helm version
    - |
      for d in `find . -name 'Chart.yaml' -type f |xargs -n 1 dirname`;do
        
        # helm lint
        echo -e "${TXT_GREEN} helm lint $d ${TXT_CLEAR}"
        helm lint $d

        # package & upload
        PKG=`basename ${d}`
        PKG_VER=`cat ${d}/Chart.yaml | awk '/version/ {print $2}'`
        PKG_HELM="${PKG}-$PKG_VER.tgz"

        helm package ${d} && \
        curl --data-binary "@${PKG_HELM}" ${HELM_REPO_SERVER}${HELM_REPO_URI}
      done
